import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	alias: {
		'@xenova/transformers': './node_modules/@xenova/transformers/src/transformers.js',
	},
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
	},
	loader: {
		'.wasm': 'binary',
	},
	plugins: [
		{
			name: 'node-polyfills',
			setup(build) {
				// Handle Node.js built-in modules that might be used by dependencies
				build.onResolve({ filter: /^(path|fs|crypto|buffer|stream|util)$/ }, () => ({
					path: 'empty',
					namespace: 'empty-module',
				}));
				
				build.onLoad({ filter: /.*/, namespace: 'empty-module' }, () => ({
					contents: 'export default {}',
				}));
			},
		},
	],
});

// Copy notification.mp3 if it exists
const notificationSoundSrc = path.join(process.cwd(), 'notification.mp3');
const notificationSoundDest = path.join(process.cwd(), 'notification.mp3');

if (fs.existsSync(notificationSoundSrc) && notificationSoundSrc !== notificationSoundDest) {
	fs.copyFileSync(notificationSoundSrc, notificationSoundDest);
	console.log('Copied notification.mp3 to output directory');
}

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
